In [42]:
#共轭梯度法
import numpy as np
import matplotlib.pyplot as plt


def ConjugateGradient(A, x, b): 
    k = 0
    r = b - np.dot(A,x)
    d = r
    
    while True:   
        k+=1
        alpha = np.linalg.norm(r)**2 / np.vdot(np.dot(A,d),d)        
        x = x + alpha * d
        old_r = r
        r = b - np.dot(A,x)
        f = 1/2 * np.dot(np.dot(x.T,A),x) - np.dot(b.T, x) 
        print("第",k,"次迭代:",f)
        if np.linalg.norm(r) < 1e-6:
            
            print("conjugate gradient finished!")
            
            return x,f
            
        else:
            beta = np.linalg.norm(r)**2/np.linalg.norm(old_r)**2            
            d = r + beta * d  
        
        
           


A = np.array([[ 56,   5,  -2,  12,   9,  -5, -10,  11,   1, -12],
           [  5,  58,  -1,  10,   3, -11,  -4, -16, -17,   5],
           [ -2,  -1,  67,   9,  10,  -4,  -6,   6,   6,  -1],
           [ 12,  10,   9,  37,  22,   9,  15,  -1,   1, -9],
           [  9,   3,  10,  22,  64,  -8,  -4, -11,   3,   0],
           [ -5, -11,  -4,   9,  -8,  62,   4,   9,  -5,  -1],
           [-10,  -4,  -6,  15,  -4,   4,  43,   4,   3,  -3],
           [ 11, -16,   6,  -1, -11,   9,   4,  43, -16,  -3],
           [  1, -17,   6,   1,   3,  -5,   3, -16,  61,   2],
           [-12,   5,  -1,  -9,   0,  -1,  -3,  -3,   2,  57]])

x = np.array([[1,1,1,1,1,1,1,1,1,1]]).T

b = np.array([[2, 6, 3, 8, -1, 9, 2, 13, 15,-9]]).T

ConjugateGradient(A, x, b)



第 1 次迭代: [[10.75325608]]
第 2 次迭代: [[-10.74230282]]
第 3 次迭代: [[-12.55740652]]
第 4 次迭代: [[-13.34753309]]
第 5 次迭代: [[-13.83649208]]
第 6 次迭代: [[-13.86602484]]
第 7 次迭代: [[-13.88567585]]
第 8 次迭代: [[-13.88601932]]
第 9 次迭代: [[-13.88603251]]
第 10 次迭代: [[-13.88603272]]
conjugate gradient finished!


(array([[-0.31704918],
        [ 0.57577052],
        [-0.13709436],
        [ 0.11684474],
        [ 0.10757077],
        [ 0.1461028 ],
        [-0.18187742],
        [ 0.86721983],
        [ 0.67423075],
        [-0.24412747]]), array([[-13.88603272]]))

In [50]:
#最速下降法
import numpy as np
import matplotlib.pyplot as plt

def SteepestDescent(A, x, b):
    k = 0
    gradient = np.dot(A, x) - b
    
    while True:
        k +=1
        alpha = np.dot(gradient.T, gradient) / np.dot(np.dot(gradient.T, A), gradient)
        old_x = x
        x = old_x - alpha * gradient
        gradient = np.dot(A, x) - b
        f = 1/2 * np.dot(np.dot(x.T,A),x) - np.dot(b.T, x) 
        print("第",k,"次迭代:",f)
        
        if np.linalg.norm(x - old_x) <1e-6:
            print("Gradient Descent Fishend!")
            return x,f
        
A = np.array([[ 56,   5,  -2,  12,   9,  -5, -10,  11,   1, -12],
           [  5,  58,  -1,  10,   3, -11,  -4, -16, -17,   5],
           [ -2,  -1,  67,   9,  10,  -4,  -6,   6,   6,  -1],
           [ 12,  10,   9,  37,  22,   9,  15,  -1,   1, -9],
           [  9,   3,  10,  22,  64,  -8,  -4, -11,   3,   0],
           [ -5, -11,  -4,   9,  -8,  62,   4,   9,  -5,  -1],
           [-10,  -4,  -6,  15,  -4,   4,  43,   4,   3,  -3],
           [ 11, -16,   6,  -1, -11,   9,   4,  43, -16,  -3],
           [  1, -17,   6,   1,   3,  -5,   3, -16,  61,   2],
           [-12,   5,  -1,  -9,   0,  -1,  -3,  -3,   2,  57]])

x = np.array([[1,1,1,1,1,1,1,1,1,1]]).T

b = np.array([[2, 6, 3, 8, -1, 9, 2, 13, 15,-9]]).T
        
SteepestDescent(A, x, b)        

第 1 次迭代: [[10.75325608]]
第 2 次迭代: [[-8.86204433]]
第 3 次迭代: [[-11.9095919]]
第 4 次迭代: [[-12.72949547]]
第 5 次迭代: [[-13.11738546]]
第 6 次迭代: [[-13.36779043]]
第 7 次迭代: [[-13.53433277]]
第 8 次迭代: [[-13.64617809]]
第 9 次迭代: [[-13.72172627]]
第 10 次迭代: [[-13.77305921]]
第 11 次迭代: [[-13.80809624]]
第 12 次迭代: [[-13.83212001]]
第 13 次迭代: [[-13.84864866]]
第 14 次迭代: [[-13.86005925]]
第 15 次迭代: [[-13.86795626]]
第 16 次迭代: [[-13.87343501]]
第 17 次迭代: [[-13.87724279]]
第 18 次迭代: [[-13.87989382]]
第 19 次迭代: [[-13.8817418]]
第 20 次迭代: [[-13.88303153]]
第 21 次迭代: [[-13.88393244]]
第 22 次迭代: [[-13.88456225]]
第 23 次迭代: [[-13.88500282]]
第 24 次迭代: [[-13.88531117]]
第 25 次迭代: [[-13.88552707]]
第 26 次迭代: [[-13.88567829]]
第 27 次迭代: [[-13.88578425]]
第 28 次迭代: [[-13.88585851]]
第 29 次迭代: [[-13.88591056]]
第 30 次迭代: [[-13.88594705]]
第 31 次迭代: [[-13.88597263]]
第 32 次迭代: [[-13.88599058]]
第 33 次迭代: [[-13.88600316]]
第 34 次迭代: [[-13.88601198]]
第 35 次迭代: [[-13.88601817]]
第 36 次迭代: [[-13.88602251]]
第 37 次迭代: [[-13.88602556]]
第 38 次迭代: [[-1

(array([[-0.31704858],
        [ 0.57577109],
        [-0.13709404],
        [ 0.11684237],
        [ 0.10757146],
        [ 0.14610353],
        [-0.18187607],
        [ 0.86721981],
        [ 0.67423084],
        [-0.24412767]]), array([[-13.88603272]]))

In [70]:
#牛顿法
import numpy as np
from sympy import *
import matplotlib.pyplot as plt

def Newtown(A, x, b):
    k = 0
    gradient =  np.dot(A, x) - b
    
    while True:
        k+=1        
        old_x = x
        x = old_x - np.dot(np.linalg.inv(A) , gradient)
        gradient =  np.dot(A, x) - b
        f = 1/2 * np.dot(np.dot(x.T,A),x) - np.dot(b.T, x) 
        print("第",k,"次迭代:",f)
        
        if np.linalg.norm(x - old_x) < 1e-6:
            print("Gradient Descent Fishend!")
            return x,f

        
A = np.array([[ 56,   5,  -2,  12,   9,  -5, -10,  11,   1, -12],
           [  5,  58,  -1,  10,   3, -11,  -4, -16, -17,   5],
           [ -2,  -1,  67,   9,  10,  -4,  -6,   6,   6,  -1],
           [ 12,  10,   9,  37,  22,   9,  15,  -1,   1, -9],
           [  9,   3,  10,  22,  64,  -8,  -4, -11,   3,   0],
           [ -5, -11,  -4,   9,  -8,  62,   4,   9,  -5,  -1],
           [-10,  -4,  -6,  15,  -4,   4,  43,   4,   3,  -3],
           [ 11, -16,   6,  -1, -11,   9,   4,  43, -16,  -3],
           [  1, -17,   6,   1,   3,  -5,   3, -16,  61,   2],
           [-12,   5,  -1,  -9,   0,  -1,  -3,  -3,   2,  57]])

x = np.array([[1111,1,1111,1,1,1,1111,1,1,1]]).T

b = np.array([[2, 6, 3, 8, -1, 9, 2, 13, 15,-9]]).T

Newtown(A, x, b)

第 1 次迭代: [[-13.88603272]]
第 2 次迭代: [[-13.88603272]]
Gradient Descent Fishend!


(array([[-0.31704918],
        [ 0.57577052],
        [-0.13709436],
        [ 0.11684474],
        [ 0.10757077],
        [ 0.1461028 ],
        [-0.18187742],
        [ 0.86721983],
        [ 0.67423075],
        [-0.24412747]]), array([[-13.88603272]]))